#!/bin/sh

set -eu
cd "$(git rev-parse --show-toplevel)"

panic() {
  echo "$1" >&2
  exit 1
}

if git status --porcelain -unormal | grep .; then
  panic "there are uncommitted changes"
fi

cd server
go vet
go build
go test
