#!/bin/sh

set -eu

panic() {
  echo "$1" >&2
  exit 1
}

cd "$(git rev-parse --show-toplevel)"

if git status --porcelain -unormal | grep .; then
  panic "there are uncommitted changes"
fi

if ! RUSTFLAGS="-D warnings" cargo check --quiet; then
  panic "cargo check failed"
fi
